export const provinces = [
	{ key: 'agrigento', name: 'Agrigento', code: 'AG', region: 'Sicilia' },
	{ key: 'alessandria', name: 'Alessandria', code: 'AL', region: 'Piemonte' },
	{ key: 'ancona', name: 'Ancona', code: 'AN', region: 'Marche' },
	{ key: 'aosta', name: 'Aosta', code: 'AO', region: 'Valle d\'Aosta' },
	{ key: 'arezzo', name: 'Arezzo', code: 'AR', region: 'Toscana' },
	{ key: 'ascoli', name: 'Ascoli Piceno', code: 'AP', region: 'Marche' },
	{ key: 'asti', name: 'Asti', code: 'AT', region: 'Piemonte' },
	{ key: 'avellino', name: 'Avellino', code: 'AV', region: 'Campania' },
	{ key: 'bari', name: 'Bari', code: 'BA', region: 'Puglia' },
	{ key: 'barletta-andria-trani', name: 'Barletta-Andria-Trani', code: 'BT', region: 'Puglia' },
	{ key: 'belluno', name: 'Belluno', code: 'BL', region: 'Veneto' },
	{ key: 'benevento', name: 'Benevento', code: 'BN', region: 'Campania' },
	{ key: 'bergamo', name: 'Bergamo', code: 'BG', region: 'Lombardia' },
	{ key: 'biella', name: 'Biella', code: 'BI', region: 'Piemonte' },
	{ key: 'bologna', name: 'Bologna', code: 'BO', region: 'Emilia-Romagna' },
	{ key: 'bolzano', name: 'Bolzano', code: 'BZ', region: 'Trentino-Alto Adige' },
	{ key: 'brescia', name: 'Brescia', code: 'BS', region: 'Lombardia' },
	{ key: 'brindisi', name: 'Brindisi', code: 'BR', region: 'Puglia' },
	{ key: 'cagliari', name: 'Cagliari', code: 'CA', region: 'Sardegna' },
	{ key: 'caltanissetta', name: 'Caltanissetta', code: 'CL', region: 'Sicilia' },
	{ key: 'campobasso', name: 'Campobasso', code: 'CB', region: 'Molise' },
	{ key: 'caserta', name: 'Caserta', code: 'CE', region: 'Campania' },
	{ key: 'catania', name: 'Catania', code: 'CT', region: 'Sicilia' },
	{ key: 'catanzaro', name: 'Catanzaro', code: 'CZ', region: 'Calabria' },
	{ key: 'chieti', name: 'Chieti', code: 'CH', region: 'Abruzzo' },
	{ key: 'como', name: 'Como', code: 'CO', region: 'Lombardia' },
	{ key: 'cosenza', name: 'Cosenza', code: 'CS', region: 'Calabria' },
	{ key: 'cremona', name: 'Cremona', code: 'CR', region: 'Lombardia' },
	{ key: 'crotone', name: 'Crotone', code: 'KR', region: 'Calabria' },
	{ key: 'cuneo', name: 'Cuneo', code: 'CN', region: 'Piemonte' },
	{ key: 'enna', name: 'Enna', code: 'EN', region: 'Sicilia' },
	{ key: 'fermo', name: 'Fermo', code: 'FM', region: 'Marche' },
	{ key: 'ferrara', name: 'Ferrara', code: 'FE', region: 'Emilia-Romagna' },
	{ key: 'firenze', name: 'Firenze', code: 'FI', region: 'Toscana' },
	{ key: 'foggia', name: 'Foggia', code: 'FG', region: 'Puglia' },
	{ key: 'forlì-Cesena', name: 'Forlì-Cesena', code: 'FC', region: 'Emilia-Romagna' },
	{ key: 'frosinone', name: 'Frosinone', code: 'FR', region: 'Lazio' },
	{ key: 'genova', name: 'Genova', code: 'GE', region: 'Liguria' },
	{ key: 'gorizia', name: 'Gorizia', code: 'GO', region: 'Friuli-Venezia Giulia' },
	{ key: 'grosseto', name: 'Grosseto', code: 'GR', region: 'Toscana' },
	{ key: 'imperia', name: 'Imperia', code: 'IM', region: 'Liguria' },
	{ key: 'isernia', name: 'Isernia', code: 'IS', region: 'Molise' },
	{ key: 'l-aquila', name: 'L\'Aquila', code: 'AQ', region: 'Abruzzo' },
	{ key: 'la-spezia', name: 'La Spezia', code: 'SP', region: 'Liguria' },
	{ key: 'latina', name: 'Latina', code: 'LT', region: 'Lazio' },
	{ key: 'lecce', name: 'Lecce', code: 'LE', region: 'Puglia' },
	{ key: 'lecco', name: 'Lecco', code: 'LC', region: 'Lombardia' },
	{ key: 'livorno', name: 'Livorno', code: 'LI', region: 'Toscana' },
	{ key: 'lodi', name: 'Lodi', code: 'LO', region: 'Lombardia' },
	{ key: 'lucca', name: 'Lucca', code: 'LU', region: 'Toscana' },
	{ key: 'macerata', name: 'Macerata', code: 'MC', region: 'Marche' },
	{ key: 'mantova', name: 'Mantova', code: 'MN', region: 'Lombardia' },
	{ key: 'massa-carrara', name: 'Massa-Carrara', code: 'MS', region: 'Toscana' },
	{ key: 'matera', name: 'Matera', code: 'MT', region: 'Basilicata' },
	{ key: 'messina', name: 'Messina', code: 'ME', region: 'Sicilia' },
	{ key: 'milano', name: 'Milano', code: 'MI', region: 'Lombardia' },
	{ key: 'modena', name: 'Modena', code: 'MO', region: 'Emilia-Romagna' },
	{ key: 'monza-e-brianza', name: 'Monza e Brianza', code: 'MB', region: 'Lombardia' },
	{ key: 'napoli', name: 'Napoli', code: 'NA', region: 'Campania' },
	{ key: 'novara', name: 'Novara', code: 'NO', region: 'Piemonte' },
	{ key: 'nuoro', name: 'Nuoro', code: 'NU', region: 'Sardegna' },
	{ key: 'oristano', name: 'Oristano', code: 'OR', region: 'Sardegna' },
	{ key: 'padova', name: 'Padova', code: 'PD', region: 'Veneto' },
	{ key: 'palermo', name: 'Palermo', code: 'PA', region: 'Sicilia' },
	{ key: 'parma', name: 'Parma', code: 'PR', region: 'Emilia-Romagna' },
	{ key: 'pavia', name: 'Pavia', code: 'PV', region: 'Lombardia' },
	{ key: 'perugia', name: 'Perugia', code: 'PG', region: 'Umbria' },
	{ key: 'pesaro-e-urbino', name: 'Pesaro e Urbino', code: 'PU', region: 'Marche' },
	{ key: 'pescara', name: 'Pescara', code: 'PE', region: 'Abruzzo' },
	{ key: 'piacenza', name: 'Piacenza', code: 'PC', region: 'Emilia-Romagna' },
	{ key: 'pisa', name: 'Pisa', code: 'PI', region: 'Toscana' },
	{ key: 'pistoia', name: 'Pistoia', code: 'PT', region: 'Toscana' },
	{ key: 'pordenone', name: 'Pordenone', code: 'PN', region: 'Friuli-Venezia Giulia' },
	{ key: 'potenza', name: 'Potenza', code: 'PZ', region: 'Basilicata' },
	{ key: 'prato', name: 'Prato', code: 'PO', region: 'Toscana' },
	{ key: 'ragusa', name: 'Ragusa', code: 'RG', region: 'Sicilia' },
	{ key: 'ravenna', name: 'Ravenna', code: 'RA', region: 'Emilia-Romagna' },
	{ key: 'reggio-calabria', name: 'Reggio Calabria', code: 'RC', region: 'Calabria' },
	{ key: 'reggio-emilia', name: 'Reggio Emilia', code: 'RE', region: 'Emilia-Romagna' },
	{ key: 'rieti', name: 'Rieti', code: 'RI', region: 'Lazio' },
	{ key: 'rimini', name: 'Rimini', code: 'RN', region: 'Emilia-Romagna' },
	{ key: 'roma', name: 'Roma', code: 'RM', region: 'Lazio' },
	{ key: 'rovigo', name: 'Rovigo', code: 'RO', region: 'Veneto' },
	{ key: 'salerno', name: 'Salerno', code: 'SA', region: 'Campania' },
	{ key: 'sassari', name: 'Sassari', code: 'SS', region: 'Sardegna' },
	{ key: 'savona', name: 'Savona', code: 'SV', region: 'Liguria' },
	{ key: 'siena', name: 'Siena', code: 'SI', region: 'Toscana' },
	{ key: 'siracusa', name: 'Siracusa', code: 'SR', region: 'Sicilia' },
	{ key: 'sondrio', name: 'Sondrio', code: 'SO', region: 'Lombardia' },
	{ key: 'sud-sardegna', name: 'Sud Sardegna', code: 'SU', region: 'Sardegna' },
	{ key: 'taranto', name: 'Taranto', code: 'TA', region: 'Puglia' },
	{ key: 'teramo', name: 'Teramo', code: 'TE', region: 'Abruzzo' },
	{ key: 'terni', name: 'Terni', code: 'TR', region: 'Umbria' },
	{ key: 'torino', name: 'Torino', code: 'TO', region: 'Piemonte' },
	{ key: 'trapani', name: 'Trapani', code: 'TP', region: 'Sicilia' },
	{ key: 'trento', name: 'Trento', code: 'TN', region: 'Trentino-Alto Adige' },
	{ key: 'treviso', name: 'Treviso', code: 'TV', region: 'Veneto' },
	{ key: 'trieste', name: 'Trieste', code: 'TS', region: 'Friuli-Venezia Giulia' },
	{ key: 'udine', name: 'Udine', code: 'UD', region: 'Friuli-Venezia Giulia' },
	{ key: 'varese', name: 'Varese', code: 'VA', region: 'Lombardia' },
	{ key: 'venezia', name: 'Venezia', code: 'VE', region: 'Veneto' },
	{ key: 'verbano-cusio-ossola', name: 'Verbano-Cusio-Ossola', code: 'VB', region: 'Piemonte' },
	{ key: 'vercelli', name: 'Vercelli', code: 'VC', region: 'Piemonte' },
	{ key: 'verona', name: 'Verona', code: 'VR', region: 'Veneto' },
	{ key: 'vibo-valentia', name: 'Vibo Valentia', code: 'VV', region: 'Calabria' },
	{ key: 'vicenza', name: 'Vicenza', code: 'VI', region: 'Veneto' },
	{ key: 'viterbo', name: 'Viterbo', code: 'VT', region: 'Lazio' },
]
